# Generated by Django 5.2 on 2025-09-22 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('instructions', models.TextField(verbose_name='Instrucciones de preparación')),
                ('prep_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de preparación (minutos)')),
                ('cook_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo de cocción (minutos)')),
                ('servings', models.PositiveIntegerField(default=1, verbose_name='Porciones')),
                ('difficulty', models.CharField(choices=[('facil', 'Fácil'), ('intermedio', 'Intermedio'), ('dificil', 'Difícil')], default='facil', max_length=20, verbose_name='Dificultad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicada')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recipes/', verbose_name='Imagen')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.recipe')),
            ],
            options={
                'verbose_name': 'Imagen de receta',
                'verbose_name_plural': 'Imágenes de receta',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100, verbose_name='Cantidad')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='main.recipe')),
            ],
            options={
                'verbose_name': 'Ingrediente de receta',
                'verbose_name_plural': 'Ingredientes de receta',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='main.RecipeIngredient', to='main.ingredient', verbose_name='Ingredientes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag', verbose_name='Etiquetas'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_ingredients', models.ManyToManyField(blank=True, to='main.ingredient', verbose_name='Ingredientes favoritos')),
                ('favorite_tags', models.ManyToManyField(blank=True, to='main.tag', verbose_name='Etiquetas favoritas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de usuario',
                'verbose_name_plural': 'Preferencias de usuario',
            },
        ),
        migrations.CreateModel(
            name='UserSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=200, verbose_name='Término de búsqueda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredients_searched', models.ManyToManyField(blank=True, to='main.ingredient')),
                ('tags_searched', models.ManyToManyField(blank=True, to='main.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de búsqueda',
                'verbose_name_plural': 'Historial de búsquedas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Me gusta',
                'verbose_name_plural': 'Me gusta',
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
